Feature/authorization
Social-projects-Rivne/Event.me pull request #11
Opened 2018-08-01 11:00 UTC by Merteg

Now, all you need for protection your resources, it's create a resource class and implement __acl__ method. This method must generate a sequence of ACE tuples.
> An access control entry (ACE) is a three-tuple that describes three things: an action (one of either Allow or Deny), a principal (a string describing a user or group), and a permission. For example the ACE, (Allow, 'bob', 'read').

2018-08-01 12:06 UTC, serge30 requested changes

2018-08-01 12:06 UTC, serge30 commented on server/server/models/token.py
> +            token = request.headers['Authorization'].split(' ')[1]
It would be better to send already extracted token to this method instead of `request`

2018-08-01 12:06 UTC, serge30 commented on server/server/models/user.py
> +        role_obj = request.dbsession.query(Role).get(self.role_id)
You need to use SQLAlchemy's capabilities to handle relations. There is `roles = relationship("Role", foreign_keys=(role_id,))` (but I have no idea why it's in plural form) and you should use it.

2018-08-01 14:11 UTC, serge30 requested changes

2018-08-01 14:11 UTC, serge30 commented on server/server/security.py
> +        userid = Token.get_user_id(request)
Do not forget to update token's expiration time on login.

2018-08-01 15:58 UTC, Merteg commented on server/server/models/token.py
> +            token = request.headers['Authorization'].split(' ')[1]
I need a `request` in this method, because I need a connection to db for getting `user_id` by token.

2018-08-01 19:46 UTC, RayMet approved these changes
Nice

2018-08-01 19:55 UTC, serge30 commented on server/server/models/token.py
> +            token = request.headers['Authorization'].split(' ')[1]
Yep, but the main idea that `Token` model should only know about how to store tokens in DB, but know nothing about way how to extract token from `request`. So it's a good to send `request` for DB session, and string with already extracted token.

2018-08-01 19:57 UTC, Merteg commented on server/server/models/token.py
> +            token = request.headers['Authorization'].split(' ')[1]
Okey

2018-08-01 20:11 UTC, serge30 requested changes

2018-08-01 20:11 UTC, serge30 commented on server/server/models/token.py
> +        return token_obj
I believe:
```
return token_obj
```
does absolutely the same what does:
```
if token_obj is None:
    return None
return token_obj
```

2018-08-01 20:11 UTC, serge30 commented on server/server/security.py
> +                                request.headers['Authorization'].split(' ')[1]
You use the same snippet at least twice, so probably you may extract to the function, which returns token extarcted from request.

2018-08-02 07:34 UTC, serge30 requested changes

2018-08-02 07:34 UTC, serge30 commented on server/server/models/token.py
> +    def update(self):
`update` is not good for this method as it updates only one field, so it'd better to call it `update_expiration_date`.

2018-08-02 08:13 UTC, serge30 approved these changes

2018-08-02 08:14 UTC, merged