Feature/registration ui fix
Social-projects-Rivne/Event.me pull request #22
Opened 2018-08-21 11:08 UTC by asstelite

Registration user fix

2018-08-21 11:22 UTC, Merteg requested changes
You didn't add a red underline to inputs when the input data is invalid.

2018-08-21 11:22 UTC, Merteg commented on client/src/components/Nav/Registration.jsx
> +             }else{
Please add spaces `} else {` for better readable.

2018-08-21 11:22 UTC, Merteg commented on client/src/components/Nav/Registration.jsx
> +                 this.state.msg !== "We sent token to your email address"
I understand it but seems really strange, better to send status: true/false from a server and handle it here.

2018-08-21 11:23 UTC, RayMet requested changes

2018-08-21 11:23 UTC, RayMet commented on client/src/components/Nav/Registration.jsx
>          let register_data = {
name of "register_data" must be something like that "registerData"

2018-08-22 10:07 UTC, RayMet approved these changes

2018-08-22 10:23 UTC, Merteg commented on client/src/components/ConfirmEmail.jsx
> +                    this.state.msg === "Your email address is confirmed"
I still think better to send boolean status from a server.

2018-08-22 10:23 UTC, Merteg commented on client/src/components/ConfirmEmail.jsx
> +                                  "Your email address is confirmed, please press the Home button and Log in"})
Wrong identation

2018-08-22 10:23 UTC, Merteg commented on client/src/components/Nav/Registration.jsx
> +                 this.setState({check_nickname: 'invalid nickname'})
Better to start phrase from uppercase letter

2018-08-22 10:23 UTC, Merteg commented on client/src/components/Nav/index.jsx
> +    }
Why did you add spaces?

2018-08-22 11:57 UTC, yazhyvyi approved these changes

2018-08-22 11:58 UTC, merged