Feature/subscribe event
Social-projects-Rivne/Event.me pull request #37
Opened 2018-09-07 13:47 UTC by YaZhyvyi

Subscribe feature, also able to view subscribed users (if logged in)

2018-09-08 10:18 UTC, Merteg requested changes
Hey, this doesn't work, I mean absolutely. You don't have subscribe view.

2018-09-08 10:18 UTC, Merteg commented on client/.gitignore
> +package-lock.json
I don't think, this file must be here

2018-09-08 10:18 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +        if (data.subscriptions !== null) {
if (data.subscriptions) seems better

2018-09-08 10:18 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +            subs: null
When you define this state, you write `subs: []`, but here `subs: null`, why?

2018-09-08 10:18 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +    sub_label: 'Subscribe',
I'm not sure but may be better to leave this states empty by default, you set this data in componentDidMount method.

2018-09-08 10:18 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +          'action': false,
`action`, what it means? I'm don't understand.

2018-09-08 10:18 UTC, Merteg commented on client/src/components/Home.jsx
> +import React, { Component } from 'react';
Why did you raise this file from the dead?

2018-09-08 11:10 UTC, serge30 commented on client/src/components/EventPage/index.jsx
> +      if (this.state.is_subbed === true) {
Why? What is the reasons  to compare bool variable to `true` or `false`?

2018-09-11 12:47 UTC, YaZhyvyi commented
Update

2018-09-11 13:00 UTC, Merteg requested changes

2018-09-11 13:00 UTC, Merteg commented on server/server/views/subscribe.py
> +from ..models.subscribe import Subscribe
Duplicate imports

2018-09-11 13:00 UTC, Merteg commented on server/server/views/subscribe.py
> +class SubscribeView(object):
This seems like resource, can you rename it to SubscribeFactory?

2018-09-11 13:00 UTC, Merteg commented on server/server/views/subscribe.py
> +subscribe = Service(name='subscribe', path='/subscribe/{subscribe_user_id}', factory=SubscribeView, cors_origins=('http://localhost:3000',))
PEP8

2018-09-11 13:03 UTC, YaZhyvyi commented
Update

2018-09-11 13:11 UTC, YaZhyvyi commented
Update

2018-09-11 13:29 UTC, Merteg approved these changes

2018-09-11 13:34 UTC, RayMet approved these changes

2018-09-11 14:43 UTC, Merteg requested changes
Sorry, I was hurry when approving PR, now I see some problems. Also, check PEP8 in your py files.

2018-09-11 14:43 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +            sub_label: 'Subscribe'
You have this states by default, so you don't need to reset it again.

2018-09-11 14:43 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +            subs: []
Also, `subs: []` by default

2018-09-11 14:43 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +          if (element.avatar === null) {
You duplicate much code here just for an avatar. Better to set it to some variable and just call it later.
Like this: `let avatar = element.avatar === null ? "/person.jpg" : element.avatar` and later ...`src={avatar}`...

2018-09-11 14:43 UTC, Merteg commented on server/server/models/subscribe.py
> +        return subscription
You don't need to create new variable, just `return request.dbsession.query(cls).filter_by(**kwargs).one_or_none()`

2018-09-11 14:43 UTC, Merteg commented on server/server/views/event.py
> +                id_array = [obj.user_id for obj in subscriptions]
You can get user objects by the relationships, without id_array.

2018-09-12 11:50 UTC, YaZhyvyi commented
Update

2018-09-12 11:52 UTC, Merteg approved these changes
Goooood, I think

2018-09-12 12:22 UTC, merged