Feature/view profile history
Social-projects-Rivne/Event.me pull request #43
Opened 2018-09-13 16:47 UTC by YaZhyvyi

2018-09-13 19:08 UTC, Merteg requested changes
![image](https://user-images.githubusercontent.com/18135784/45509869-606a5880-b7a1-11e8-9223-dafa79d0ace2.png)
Please, don't add images like this, we also have theirs in other, nested, folder.

2018-09-13 19:08 UTC, Merteg commented on client/.gitignore
> +package-lock.json
Why do you add this file to gitignore?

2018-09-13 19:08 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +          'user_id': sessionStorage['User-id']
You don't need to duplicate 'event_id' and 'user_id' in this `if`, you can assign a value to it outside of `if` statement.

2018-09-13 19:08 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +          if (data.is_subbed) {
You can unite this `if`'s.

2018-09-13 19:08 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +        this.setState({
Also, you don't need to separate this setState and previous.

2018-09-13 19:08 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +          let avatar = element.avatar === null ? "/person.jpg" : element.avatar
When you don't change a variable, better to use `const`. [Style Guide](https://github.com/airbnb/javascript/#references--prefer-const)

2018-09-13 19:08 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +  SubscribeEvent = (eve) => {
Hmm, `subscribeEvent` seems better))
[Guide](https://github.com/airbnb/javascript/#naming--camelCase)

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +          console.log("DATA: " + data)
Remove console.log. All console.log's

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +              this.setState({  })
Remove this.

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +                <a
Are you sure that the `Link` doesn't work here?

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +                    image={
You don't need to add line break here

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +                  this.state.user.avatar ===
Don't separate statement like this. [Guide](https://github.com/airbnb/javascript/#control-statements)

2018-09-13 19:08 UTC, Merteg commented on client/src/components/Profile.jsx
> +            <h4 className="title-profile">Profile&nbsp;&nbsp;<span                  className="profile-title-nick">@{this.state.user.nickname}</span>
Many many useless white spaces.

2018-09-13 19:08 UTC, Merteg commented on server/server/views/event.py
> +            response['status_str'] = self.event_status
This expression must be outside of if statement. This is very important.

2018-09-13 19:08 UTC, Merteg commented on server/server/views/profile-history.py
> +from cornice.resource import Service
This file name does not meet the PEP8 ( I talk about profile-history.py) [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)

2018-09-13 19:08 UTC, Merteg commented on server/server/views/profile-history.py
> +    response['success'] = True
You don't need to separate these expressions.

2018-09-13 19:47 UTC, Merteg commented
![image](https://user-images.githubusercontent.com/18135784/45511770-9100c100-b7a6-11e8-989c-ab622cf24a96.png)
Please resolve these warnings. 
![image](https://user-images.githubusercontent.com/18135784/45511846-c4435000-b7a6-11e8-8d49-88668b29c553.png)
I like this design, really, but there is a small (or not) problem with images.
![image](https://user-images.githubusercontent.com/18135784/45511907-f2289480-b7a6-11e8-9a62-3cda5f67ddb7.png)
Also, there are many warnings in the console, at profile page, resolve it.

2018-09-13 19:53 UTC, Merteg commented
Also, unsubscribe don't work immediately.
I mean, when I click on `Subscribe` it's changing to `Unsubscribe`, but when I click on `Unsubscribe` it's not.
![image](https://user-images.githubusercontent.com/18135784/45512158-9f9ba800-b7a7-11e8-9953-4180f34d7f1f.png)
I have a 1366x768 screen resolution, and it seems bad on this. Can you resolve it?

2018-09-14 08:18 UTC, YaZhyvyi commented
Update

2018-09-14 11:41 UTC, Merteg reviewed
Also, resolve merge conflicts.

2018-09-14 11:41 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +      'if_subbed': null
You can set 'if_subbed' true by default. After this, you don't need an else statement.

2018-09-14 11:41 UTC, Merteg commented on client/src/components/EventPage/index.jsx
> +                         null ? "img/person.jpg" : element.avatar
Why do you add a line break?

2018-09-14 12:13 UTC, YaZhyvyi commented
Update

2018-09-14 12:15 UTC, Merteg approved these changes

2018-09-14 12:17 UTC, RayMet approved these changes

2018-09-14 12:25 UTC, merged