Feature/log in out
Social-projects-Rivne/Event.me pull request #7
Opened 2018-07-27 16:27 UTC by Merteg

Add two routes and two views for log-in and log-out. Add new table for tokens storage. Add seeds and migrations.

2018-07-27 19:03 UTC, RayMet approved these changes
Астанавітесь!

2018-07-27 19:15 UTC, serge30 requested changes

2018-07-27 19:15 UTC, serge30 commented on server/server/models/user.py
> +    unban_date = Column(DateTime)
`banned_to_date` sounds better

2018-07-27 19:15 UTC, serge30 commented on server/server/models/token.py
> +                        expiration_date=datetime.now()+timedelta(days=7))
[Magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) is an evil :) Please extract `7` to constant with meaningful name

2018-07-27 19:15 UTC, serge30 commented on server/server/models/token.py
> +    def add_token(cls, req, token, user_id):
Try to do not shorten variables/parameters names, `request` is not so long. And it's the same for other methods below.

2018-07-27 19:15 UTC, serge30 commented on server/server/models/user.py
> +        if(user_status.status == "Active"):
Python is not JavaScript, you don't need parentheses around condition for `if` statement: [ref](https://docs.python.org/2.7/tutorial/controlflow.html#if-statements)

2018-07-27 19:15 UTC, serge30 commented on server/server/views/authen.py
> +from passlib.totp import generate_secret
Pleaaaase, do not shorten modules names too. I agree that `authentication` is bit long module name, but you'd better use common shortening as `auth`.

2018-07-27 19:15 UTC, serge30 commented on server/server/views/authen.py
> +    if(Token.deactivate(request, request.headers['Authorization-token'])):
What if `Authorization-token` header is missing in request? Also we may consider using a standard [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) HTTP header for this.

2018-07-27 19:15 UTC, serge30 commented on server/config.py
> +run = subprocess.Popen(seed_roles.split(), stdout=subprocess.PIPE)
I cannot get, why you need to call as subprocess python script, why not just to import it and run a function? You don't have to fix it in scope of this PR, but it is something we need to discuss and re-work in future.

2018-07-28 16:46 UTC, serge30 requested changes

2018-07-28 16:46 UTC, serge30 commented on server/server/models/user.py
> +from .user_status import UserStatus
According to [PEP-8](https://www.python.org/dev/peps/pep-0008/#imports):
> Imports should be grouped in the following order:
>
>Standard library imports.
>Related third party imports.
>Local application/library specific imports.
>
>You should put a blank line between each group of imports.

2018-07-28 16:46 UTC, serge30 commented on server/migrations/env.py
> +from server.models import category, event_history, event_status, event_tag, event, feedback, gallery, role, subscribe, tag, user_status, user, token
According to [PEP-8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length):
> Limit all lines to a maximum of 79 characters.

2018-07-28 21:26 UTC, serge30 requested changes

2018-07-28 21:26 UTC, serge30 commented on server/migrations/env.py
> +                        subscribe, tag, user_status, user, token
PEP-8:
> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

Python ignores line ends inside brackets and parentheses, so recommendation here to wrap imports to parentheses:
```
from module import (obj1, obj2, obj3,
                    obj4, obj5)
```

2018-07-29 11:49 UTC, serge30 approved these changes

2018-07-29 12:55 UTC, merged